import { z } from 'zod';
import { classify, extractCandidates } from '../classify';
import { addr, domain, entity, normalizeUrl, safeUrl, type Snapshot } from '../model';
import { cached, request, step, type Update } from './client';
const pair=z.object({chainId:z.string(),url:z.string().url(),pairAddress:z.string(),baseToken:z.object({address:z.string(),name:z.string(),symbol:z.string()}),quoteToken:z.object({address:z.string(),name:z.string().optional(),symbol:z.string().optional()}),priceUsd:z.string().optional(),liquidity:z.object({usd:z.number().optional()}).optional(),volume:z.object({h24:z.number().optional()}).optional(),marketCap:z.number().nullish(),pairCreatedAt:z.number().optional(),info:z.object({websites:z.array(z.object({url:z.string()})).optional(),socials:z.array(z.object({url:z.string().optional(),type:z.string().optional(),platform:z.string().optional(),handle:z.string().optional()})).optional()}).optional()});
function links(p:z.infer<typeof pair>){return [...(p.info?.websites??[]),...(p.info?.socials??[])].flatMap(l=>{const value=l.url??('handle'in l&&l.handle&&['x','twitter'].includes(l.platform??'')?`https://x.com/${l.handle.replace(/^@/,'')}`:'');const url=safeUrl(value);return url?[normalizeUrl(url)]:[];});}
function publishLinks(r:Snapshot,p:z.infer<typeof pair>,root= r.root){for(const url of links(p)){let target;try{target=classify(url);}catch{continue;}const e=entity(target,target.kind==='social'?'social':'website',target.kind==='social'?new URL(url).pathname:domain(url),true);r.entities.push(e);const id=`link:${root.id}:${e.id}`;r.findings.push({id,title:e.kind==='social'?'Published social profile':'Published website',description:'The project publicly advertises this link in DEX Screener metadata. This is a reference, not proof of control, identity or endorsement.',entityIds:[root.id,e.id],category:'metadata',source:{provider:'DEX Screener',url:p.url,at:r.at,strength:'metadata'}});r.relationships.push({id,from:root.id,to:e.id,type:e.kind==='social'?'social':'website',findingId:id});}}
export async function dex(r:Snapshot,signal:AbortSignal,update:Update){
 const search=r.target.kind!=='address';const url=search?`https://api.dexscreener.com/latest/dex/search?q=${encodeURIComponent(r.target.kind==='search'?r.target.value:r.target.kind==='social'?new URL(r.target.value).pathname.slice(1):domain(r.target.value))}`:`https://api.dexscreener.com/token-pairs/v1/solana/${r.target.value}`;
 await step(search?'Searching indexed public metadata':'Fetching token markets',update,r.warnings,signal,async()=>{
  const data=search?await cached([url],z.object({pairs:z.array(pair).nullable()}),signal,s=>request(url,s)):await cached([url],z.array(pair),signal,s=>request(url,s));
  const pairs=(Array.isArray(data)?data:data.pairs??[]).filter(p=>p.chainId==='solana');
  if(r.target.kind==='search'){
   for(const p of [...new Map(pairs.map(p=>[p.baseToken.address,p])).values()].slice(0,12)){const e=entity(addr(p.baseToken.address),'token',`${p.baseToken.name} · ${p.baseToken.symbol}`,false);r.entities.push(e);r.findings.push({id:`candidate:${e.id}`,title:e.label,description:'Name/symbol search candidate. Confirm the mint address before investigating; names are not unique.',entityIds:[e.id],category:'candidate',source:{provider:'DEX Screener',url:p.url,at:r.at,strength:'insufficient'}});}r.coverage='Up to 12 Solana token search candidates. No relationship is inferred from a name match.';return;
  }
  if(['website','social'].includes(r.target.kind)){
   for(const p of pairs){if(!links(p).some(url=>r.target.kind==='social'?normalizeUrl(url)===normalizeUrl(r.target.value):domain(url)===domain(r.target.value)))continue;const root=entity(addr(p.baseToken.address),'token',`${p.baseToken.name} · ${p.baseToken.symbol}`,true);r.entities.push(root);publishLinks(r,p,root);}r.coverage='DEX Screener search results with an exact advertised social URL or matching domain. This is not a complete reverse index.';return;
  }
  const matching=pairs.filter(p=>[p.baseToken.address,p.quoteToken.address].includes(r.target.value)).sort((a,b)=>(b.liquidity?.usd??0)-(a.liquidity?.usd??0));
  const branded=matching.find(p=>p.baseToken.address===r.target.value);
  if(branded){r.root={...r.root,kind:'token',label:`${branded.baseToken.name} · ${branded.baseToken.symbol}`};r.token={...r.token,holders:r.token?.holders??[],top10:r.token?.top10??null,top20:r.token?.top20??null,top50:null,name:branded.baseToken.name,symbol:branded.baseToken.symbol,price:branded.priceUsd,liquidity:branded.liquidity?.usd,volume:branded.volume?.h24,marketCap:branded.marketCap??undefined,poolCreatedAt:branded.pairCreatedAt};r.findings.push({id:`market:${branded.pairAddress}`,title:'Largest returned pool market snapshot',description:`Price, liquidity and volume use the highest-liquidity returned base-token pool. Pool creation date is not token creation date.`,entityIds:[r.root.id],category:'metadata',source:{provider:'DEX Screener',url:branded.url,at:r.at,strength:'metadata'}});}
  for(const p of matching.slice(0,5)){const e=entity(addr(p.pairAddress),'pool',`${p.baseToken.symbol} / ${p.quoteToken.symbol??'pair'} pool`,true);r.entities.push(e);const id=`pool:${p.pairAddress}`;r.findings.push({id,title:'Associated liquidity pool',description:`Listed pool${p.liquidity?.usd!==undefined?` with $${p.liquidity.usd.toLocaleString('en-US')} reported liquidity`:''}. A pool is not an individual beneficial owner.`,entityIds:[r.root.id,e.id],category:'metadata',source:{provider:'DEX Screener',url:p.url,at:r.at,strength:'metadata'}});r.relationships.push({id,from:r.root.id,to:e.id,type:'pool',findingId:id});if(p.baseToken.address===r.target.value)publishLinks(r,p);}
 });
}
export async function publicPage(r:Snapshot,signal:AbortSignal,update:Update){
 await step('Reading public page (CORS required)',update,r.warnings,signal,async()=>{
  const response=await fetch(r.target.value,{signal:AbortSignal.any([signal,AbortSignal.timeout(10000)]),credentials:'omit',referrerPolicy:'no-referrer'}).catch(()=>{throw new Error('Direct page access is blocked or unavailable. Websites and X often require CORS permission or login. Indexed public metadata is still checked.');});
  if(!response.ok)throw new Error(`Page returned HTTP ${response.status}. No private content was accessed.`);if(!response.headers.get('content-type')?.includes('text/html'))throw new Error('No public HTML available.');
  const reader=response.body?.getReader();if(!reader)throw new Error('No page body.');let text='',bytes=0;const decoder=new TextDecoder();try{while(true){const {done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>1000000)throw new Error('Public page exceeds the 1 MB extraction limit.');text+=decoder.decode(value,{stream:true});}}finally{await reader.cancel();}
  const doc=new DOMParser().parseFromString(text,'text/html');doc.querySelectorAll('script,style,noscript').forEach(n=>n.remove());const title=doc.title.trim().slice(0,200);if(title)r.root.label=title;r.root.verified=true;
  r.findings.push({id:`page:${r.root.id}`,title:title||domain(r.target.value),description:'Public HTML was retrieved in the browser. Dynamic, authenticated and historical content is outside coverage.',entityIds:[r.root.id],category:'identity',source:{provider:'Public HTML',url:r.target.value,at:r.at,strength:'metadata'}});
  const candidates=extractCandidates(doc.body.textContent??'');for(const a of doc.querySelectorAll('a[href]')){try{const t=classify(new URL(a.getAttribute('href')!,r.target.value).href);if(t.kind==='social')candidates.push(t);}catch{/* Unsupported page references are not entities. */}}
  for(const t of [...new Map(candidates.map(t=>[t.value,t])).values()].slice(0,30)){const e=entity(t,t.kind==='social'?'social':t.kind==='website'?'website':'unknown',t.value,false);if(e.id===r.root.id)continue;r.entities.push(e);const id=`page-link:${r.root.id}:${e.id}`;r.findings.push({id,title:'Public page reference',description:'This identifier appears in page text or a link. Its mention does not establish ownership or a financial relationship.',entityIds:[r.root.id,e.id],category:'metadata',source:{provider:'Public HTML',url:r.target.value,at:r.at,strength:'metadata'}});r.relationships.push({id,from:r.root.id,to:e.id,type:e.kind==='social'?'social':e.kind==='website'?'website':'interaction',findingId:id});}
 });
}
